const hundredDaysData = [
  // ===== Basics (Days 1-5) =====
  { day: 1, name: "Palindrome Number", topic: "Basics", leetcode: "https://leetcode.com/problems/palindrome-number/", codeSolution: "https://edslash.com/leetcode-problem-9-palindrome-number/", video: "https://youtu.be/U8UnNZhoPQk" },
  { day: 2, name: "Power of 2", topic: "Basics", leetcode: "https://leetcode.com/problems/power-of-two/", codeSolution: "https://edslash.com/leetcode-problem-231-power-of-two/", video: "https://youtu.be/CoKjo8h_r3w" },
  { day: 3, name: "Fibonacci Number", topic: "Basics", leetcode: "https://leetcode.com/problems/fibonacci-number/", codeSolution: "https://edslash.com/leetcode-problem-509-fibonacci-number/", video: "https://youtu.be/zLrkxEo80kA" },
  { day: 4, name: "Tribonacci Number", topic: "Basics", leetcode: "https://leetcode.com/problems/n-th-tribonacci-number/", codeSolution: "https://edslash.com/leetcode-problem-1137-tribonacci-number/", video: "https://youtu.be/Lp8na8X5sqQ" },
  { day: 5, name: "Water Bottles", topic: "Basics", leetcode: "https://leetcode.com/problems/water-bottles/description/", codeSolution: "https://edslash.com/leetcode-problem-1518-water-bottles/", video: "https://youtu.be/VrXISj454Jc" },

  // ===== Arrays (Days 6-20) =====
  { day: 6, name: "Two Sum", topic: "Arrays", leetcode: "https://leetcode.com/problems/two-sum/", codeSolution: "https://edslash.com/leetcode-problem-1-two-sum/", video: "https://youtu.be/6zfMQVfQOds" },
  { day: 7, name: "Add to Array-Form of Integer", topic: "Arrays", leetcode: "https://leetcode.com/problems/add-to-array-form-of-integer/", codeSolution: "https://edslash.com/leetcode-problem-989-add-to-array-form-of-integer/", video: "https://youtu.be/QTCbgeSZWbY" },
  { day: 8, name: "Maximum Product of Two Elements in an Array", topic: "Arrays", leetcode: "https://leetcode.com/problems/maximum-product-of-two-elements-in-an-array/description/", codeSolution: "https://edslash.com/leetcode-problem-1464-maximum-product-of-two-elements-in-an-array/", video: "https://youtu.be/jE2Goga8cD4" },
  { day: 9, name: "Median of Two Sorted Arrays", topic: "Arrays", leetcode: "https://leetcode.com/problems/median-of-two-sorted-arrays/", codeSolution: "https://edslash.com/leetcode-problem-4-median-of-two-sorted-arrays/", video: "https://youtu.be/QpPOvwej2Eg" },
  { day: 10, name: "Missing Number", topic: "Arrays", leetcode: "https://leetcode.com/problems/missing-number/", codeSolution: "https://edslash.com/leetcode-problem-268-missing-number/", video: "https://youtu.be/P9sk05O6gNA" },
  { day: 11, name: "Remove Element", topic: "Arrays", leetcode: "https://leetcode.com/problems/remove-element/description/", codeSolution: "https://edslash.com/leetcode-problem-27-remove-element/", video: "https://youtu.be/e-lA6W7GKng" },
  { day: 12, name: "Squares of a Sorted Array", topic: "Arrays", leetcode: "https://leetcode.com/problems/squares-of-a-sorted-array/", codeSolution: "https://edslash.com/leetcode-problem-977-squares-of-a-sorted-array/", video: "https://youtu.be/yH8L4NdrvsU" },
  { day: 13, name: "Two Sum II - Input Array Is Sorted", topic: "Arrays", leetcode: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/", codeSolution: "https://edslash.com/leetcode-problem-167-two-sum-ii-input-array-is-sorted/", video: "https://youtu.be/tdlD6ijL-7w" },
  { day: 14, name: "Product of Array Except Self", topic: "Arrays", leetcode: "https://leetcode.com/problems/product-of-array-except-self/", codeSolution: "https://edslash.com/leetcode-problem-238-product-of-array-except-self/", video: "https://youtu.be/4r4rAW6pebU" },
  { day: 15, name: "Bulb Switcher", topic: "Arrays", leetcode: "https://leetcode.com/problems/bulb-switcher/", codeSolution: "https://edslash.com/leetcode-problem-319-bulb-switcher/", video: "https://youtu.be/uQM9sldV7ms" },
  { day: 16, name: "Largest Number At Least Twice of Others", topic: "Arrays", leetcode: "https://leetcode.com/problems/largest-number-at-least-twice-of-others/", codeSolution: "https://edslash.com/leetcode-problem-747-largest-number-at-least-twice-of-others/", video: "https://youtu.be/5KAiReTDzp8" },
  { day: 17, name: "Container With Most Water", topic: "Arrays", leetcode: "https://leetcode.com/problems/container-with-most-water/", codeSolution: "https://edslash.com/leetcode-problem-11-container-with-most-water/", video: "https://youtu.be/g94_MJuDsN0" },
  { day: 18, name: "Increasing Triplet Subsequence", topic: "Arrays", leetcode: "https://leetcode.com/problems/increasing-triplet-subsequence/description/", codeSolution: "https://edslash.com/leetcode-problem-334-increasing-triplet-subsequence/", video: "https://youtu.be/I5YSk0DYJrQ" },
  { day: 19, name: "Maximum Ascending Subarray Sum", topic: "Arrays", leetcode: "https://leetcode.com/problems/maximum-ascending-subarray-sum/", codeSolution: "https://edslash.com/leetcode-problem-1800-maximum-ascending-subarray-sum/", video: "https://youtu.be/TE41nLQG4cM" },
  { day: 20, name: "Find Lucky Integer in an Array", topic: "Arrays", leetcode: "https://leetcode.com/problems/find-lucky-integer-in-an-array/", codeSolution: "https://edslash.com/leetcode-problem-1394-find-lucky-integer-in-an-array/", video: "https://youtu.be/-fBcGrFjso4" },

  // ===== Binary Search (Days 21-27) =====
  { day: 21, name: "Binary Search", topic: "Binary Search", leetcode: "https://leetcode.com/problems/binary-search/", codeSolution: "https://edslash.com/leetcode-problem-704-binary-search/", video: "https://youtu.be/RQBmmr2lgs4" },
  { day: 22, name: "Find First and Last Position of Element in Sorted Array", topic: "Binary Search", leetcode: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", codeSolution: "https://edslash.com/leetcode-problem-34-find-first-and-last-position-of-element-in-sorted-array/", video: "https://youtu.be/HsSAEDhigD4" },
  { day: 23, name: "Search in Rotated Sorted Array", topic: "Binary Search", leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/", codeSolution: "https://edslash.com/leetcode-problem-33-search-in-rotated-sorted-array/", video: "https://youtu.be/Nx9BjBzAvA4" },
  { day: 24, name: "Find Minimum in Rotated Sorted Array", topic: "Binary Search", leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", codeSolution: "https://edslash.com/leetcode-problem-153-find-minimum-in-rotated-sorted-array/", video: "https://youtu.be/5_--qpoKElQ" },
  { day: 25, name: "Find Peak Element", topic: "Binary Search", leetcode: "https://leetcode.com/problems/find-peak-element/description/", codeSolution: "https://edslash.com/leetcode-problem-162-find-peak-element/", video: "https://youtu.be/e_Cwl7EYEIc" },
  { day: 26, name: "Search Insert Position", topic: "Binary Search", leetcode: "https://leetcode.com/problems/search-insert-position/", codeSolution: "https://edslash.com/leetcode-problem-35-search-insert-position/", video: "https://youtu.be/-9W4Myyqtek" },
  { day: 27, name: "Single Element in a Sorted Array", topic: "Binary Search", leetcode: "https://leetcode.com/problems/single-element-in-a-sorted-array/", codeSolution: "https://edslash.com/leetcode-problem-540-single-element-in-a-sorted-array/", video: "https://youtu.be/sqfYcZ66vkc" },

  // ===== Sorting (Days 28-36) =====
  { day: 28, name: "Sort Colors", topic: "Sorting", leetcode: "https://leetcode.com/problems/sort-colors/", codeSolution: "https://edslash.com/leetcode-problem-75-sort-colors/", video: "https://youtu.be/S6l20Rj3oFo" },
  { day: 29, name: "Maximum Subarray", topic: "Arrays", leetcode: "https://leetcode.com/problems/maximum-subarray/", codeSolution: "https://edslash.com/leetcode-problem-53-maximum-subarray/", video: "https://youtu.be/wQtYn0X4wus" },
  { day: 30, name: "Trapping Rain Water", topic: "Arrays", leetcode: "https://leetcode.com/problems/trapping-rain-water/", codeSolution: "https://edslash.com/leetcode-problem-42-trapping-rain-water/", video: "https://youtu.be/h1AeRVdQlC4" },
  { day: 31, name: "Find Target Indices After Sorting Array", topic: "Sorting", leetcode: "https://leetcode.com/problems/find-target-indices-after-sorting-array/", codeSolution: "https://edslash.com/leetcode-problem-2089-find-target-indices-after-sorting-array/", video: "https://youtu.be/LtfIWA1yCEI" },
  { day: 32, name: "Largest Number", topic: "Sorting", leetcode: "https://leetcode.com/problems/largest-number/", codeSolution: "https://edslash.com/leetcode-problem-179-largest-number/", video: "https://youtu.be/80bA8JHrikw" },
  { day: 33, name: "Maximum Count of Positive and Negative Integer", topic: "Arrays", leetcode: "https://leetcode.com/problems/maximum-count-of-positive-integer-and-negative-integer/", codeSolution: "https://edslash.com/leetcode-problem-2529-maximum-count-of-positive-integer-and-negative-integer/", video: "https://youtu.be/JYxPDYV3KF8" },
  { day: 34, name: "Plus One", topic: "Arrays", leetcode: "https://leetcode.com/problems/plus-one/", codeSolution: "https://edslash.com/leetcode-problem-66-plus-one/", video: "https://youtu.be/aG9LHsa3gO8" },
  { day: 35, name: "Kth Largest Element in an Array", topic: "Sorting", leetcode: "https://leetcode.com/problems/kth-largest-element-in-an-array/description/", codeSolution: "https://edslash.com/leetcode-problem-215-kth-largest-element-in-an-array", video: "https://youtu.be/a5kBxkr-hq0" },
  { day: 36, name: "Average Salary Excluding the Minimum and Maximum Salary", topic: "Arrays", leetcode: "https://leetcode.com/problems/average-salary-excluding-the-minimum-and-maximum-salary/", codeSolution: "https://edslash.com/leetcode-problem-1491-average-salary-excluding-the-minimum-and-maximum-salary/", video: "https://youtu.be/N5HKBu6Zj7A" },

  // ===== Stack & Queue (Days 37-40) =====
  { day: 37, name: "Min Stack", topic: "Stack & Queue", leetcode: "https://leetcode.com/problems/min-stack/", codeSolution: "https://edslash.com/leetcode-problem-155-min-stack", video: "https://youtu.be/qy0RtMfwOc4" },
  { day: 38, name: "Implement Stack using Queues", topic: "Stack & Queue", leetcode: "https://leetcode.com/problems/implement-stack-using-queues/", codeSolution: "https://edslash.com/leetcode-problem-225-implement-stack-using-queues", video: "https://youtu.be/ShEdlEIiv9o" },
  { day: 39, name: "Implement Queue using Stacks", topic: "Stack & Queue", leetcode: "https://leetcode.com/problems/implement-queue-using-stacks/description/", codeSolution: "https://edslash.com/leetcode-problem-232-implement-queue-using-stacks", video: "https://youtu.be/o0qFVCmm67o" },
  { day: 40, name: "Longest Consecutive Sequence", topic: "Arrays", leetcode: "https://leetcode.com/problems/longest-consecutive-sequence/", codeSolution: "", video: "" },

  // ===== Arrays / Sorting continued (Days 41-44) =====
  { day: 41, name: "Find the Duplicate Number", topic: "Arrays", leetcode: "https://leetcode.com/problems/find-the-duplicate-number/", codeSolution: "https://edslash.com/leetcode-problem-287-find-the-duplicate-number/", video: "https://youtu.be/veDCJIQmRuI" },
  { day: 42, name: "Last Stone Weight", topic: "Sorting", leetcode: "https://leetcode.com/problems/last-stone-weight/", codeSolution: "https://edslash.com/leetcode-problem-1046-last-stone-weight/", video: "https://youtu.be/NpN35IidF7s" },
  { day: 43, name: "Find Pivot Index", topic: "Arrays", leetcode: "https://leetcode.com/problems/find-pivot-index/", codeSolution: "https://edslash.com/leetcode-problem-724-find-pivot-index/", video: "https://youtu.be/4KDFPiYUEbg" },
  { day: 44, name: "Boats to Save People", topic: "Sorting", leetcode: "https://leetcode.com/problems/boats-to-save-people", codeSolution: "https://edslash.com/leetcode-problem-881-boats-to-save-people/", video: "https://youtu.be/H0VGglQrEJw" },

  // ===== Strings (Days 45-55) =====
  { day: 45, name: "Length of Last Word", topic: "Strings", leetcode: "https://leetcode.com/problems/length-of-last-word/", codeSolution: "https://edslash.com/leetcode-problem-58-length-of-last-word/", video: "https://youtu.be/J_JR-6BjfrM" },
  { day: 46, name: "Remove Duplicate Letters", topic: "Strings", leetcode: "https://leetcode.com/problems/remove-duplicate-letters/description/", codeSolution: "https://edslash.com/leetcode-problem-316-remove-duplicate-letters/", video: "https://youtu.be/VBXcQKzlADs" },
  { day: 47, name: "Reverse Words in a String", topic: "Strings", leetcode: "https://leetcode.com/problems/reverse-words-in-a-string/", codeSolution: "https://edslash.com/leetcode-problem-151-reverse-words-in-a-string/", video: "https://youtu.be/xC7JdzFh0xA" },
  { day: 48, name: "String Compression", topic: "Strings", leetcode: "https://leetcode.com/problems/string-compression/", codeSolution: "https://edslash.com/leetcode-problem-443-string-compression/", video: "https://youtu.be/gKUYKjgjlO4" },
  { day: 49, name: "Decode String", topic: "Strings", leetcode: "https://leetcode.com/problems/decode-string/", codeSolution: "https://edslash.com/leetcode-problem-394-decode-string/", video: "https://youtu.be/jxy0JRG5JhE" },
  { day: 50, name: "Redistribute Characters to Make All Strings Equal", topic: "Strings", leetcode: "https://leetcode.com/problems/redistribute-characters-to-make-all-strings-equal", codeSolution: "https://edslash.com/leetcode-challenge-1897-redistribute-characters-to-make-all-strings-equal/", video: "https://youtu.be/t9_QBbbpDes" },
  { day: 51, name: "Consecutive Characters", topic: "Strings", leetcode: "https://leetcode.com/problems/consecutive-characters/", codeSolution: "https://edslash.com/leetcode-problem-1446-consecutive-characters/", video: "https://youtu.be/aphoUQ3VN5o" },
  { day: 52, name: "Valid Palindrome", topic: "Strings", leetcode: "https://leetcode.com/problems/valid-palindrome/", codeSolution: "https://edslash.com/leetcode-problem-125-valid-palindrome/", video: "https://youtu.be/5sQ-OuhrXMg" },
  { day: 53, name: "Valid Parentheses", topic: "Stack & Queue", leetcode: "https://leetcode.com/problems/valid-parentheses", codeSolution: "https://edslash.com/leetcode-problem-20-valid-parentheses/", video: "https://youtu.be/imnH6hxdvEQ" },
  { day: 54, name: "Minimum Add to Make Parentheses Valid", topic: "Stack & Queue", leetcode: "https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/", codeSolution: "https://edslash.com/leetcode-problem-921-minimum-add-to-make-parentheses-valid/", video: "https://youtu.be/EQCRc1Nd4mI" },
  { day: 55, name: "Valid Anagram", topic: "Strings", leetcode: "https://leetcode.com/problems/valid-anagram/", codeSolution: "http://edslash.com/leetcode-problem-242-valid-anagram", video: "https://youtu.be/mxlqUmohM8M" },

  // ===== Matrix (Days 56-60) =====
  { day: 56, name: "Matrix Diagonal Sum", topic: "Matrix", leetcode: "https://leetcode.com/problems/matrix-diagonal-sum/description/", codeSolution: "https://edslash.com/leetcode-problem-1572-matrix-diagonal-sum", video: "https://youtu.be/32pFat5_A_s" },
  { day: 57, name: "Transpose Matrix", topic: "Matrix", leetcode: "https://leetcode.com/problems/transpose-matrix/", codeSolution: "https://edslash.com/leetcode-problem-867-transpose-matrix/", video: "https://youtu.be/rvGWJhNkPLk" },
  { day: 58, name: "Spiral Matrix II", topic: "Matrix", leetcode: "https://leetcode.com/problems/spiral-matrix-ii/", codeSolution: "https://edslash.com/leetcode-problem-59-spiral-matrix-ii/", video: "https://youtu.be/UA4xgSCWdoo" },
  { day: 59, name: "Search a 2D Matrix", topic: "Matrix", leetcode: "https://leetcode.com/problems/search-a-2d-matrix/", codeSolution: "https://edslash.com/leetcode-problem-74-search-a-2d-matrix/", video: "https://youtu.be/DWRLp_g505k" },
  { day: 60, name: "Rotate Image", topic: "Matrix", leetcode: "https://leetcode.com/problems/rotate-image/", codeSolution: "https://edslash.com/leetcode-problem-48-rotate-image/", video: "https://youtu.be/ZkMesYyVkKU" },

  // ===== Linked List (Days 61-76) =====
  { day: 61, name: "Palindrome Linked List", topic: "Linked List", leetcode: "https://leetcode.com/problems/palindrome-linked-list/", codeSolution: "https://edslash.com/leetcode-problem-234-palindrome-linked-list/", video: "https://youtu.be/ipJiTWKSTyw" },
  { day: 62, name: "Merge Two Sorted Lists", topic: "Linked List", leetcode: "https://leetcode.com/problems/merge-two-sorted-lists/description/", codeSolution: "https://edslash.com/leetcode-problem-21-merge-two-sorted-lists/", video: "https://youtu.be/9IytF_jLRLw" },
  { day: 63, name: "Remove Duplicates from Sorted List", topic: "Linked List", leetcode: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/description/", codeSolution: "https://edslash.com/leetcode-problem-83-remove-duplicates-from-sorted-list/", video: "https://youtu.be/c1WX5PB9C7A" },
  { day: 64, name: "Add Two Numbers", topic: "Linked List", leetcode: "https://leetcode.com/problems/add-two-numbers/", codeSolution: "https://edslash.com/leetcode-problem-2-add-two-numbers/", video: "https://youtu.be/SPo_FxaV_k8" },
  { day: 65, name: "Double a Number Represented as a Linked List", topic: "Linked List", leetcode: "https://leetcode.com/problems/double-a-number-represented-as-a-linked-list/", codeSolution: "https://edslash.com/leetcode-problem-2816-double-a-number-represented-as-a-linked-list/", video: "https://youtu.be/OyY8dtcQgiI" },
  { day: 66, name: "Odd Even Linked List", topic: "Linked List", leetcode: "https://leetcode.com/problems/odd-even-linked-list/description/", codeSolution: "https://edslash.com/leetcode-problem-328-odd-even-linked-list/", video: "https://youtu.be/w3x2Tw0SR38" },
  { day: 67, name: "Intersection of Two Linked Lists", topic: "Linked List", leetcode: "https://leetcode.com/problems/intersection-of-two-linked-lists/", codeSolution: "https://edslash.com/leetcode-problem-160-intersection-of-two-linked-lists/", video: "https://youtu.be/UG3nSFTllP4" },
  { day: 68, name: "Remove Nth Node from End of List", topic: "Linked List", leetcode: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", codeSolution: "https://edslash.com/leetcode-problem-19-remove-nth-node-from-end-of-list/", video: "https://youtu.be/1d_LDkavfgw" },
  { day: 69, name: "Delete Node in a Linked List", topic: "Linked List", leetcode: "https://leetcode.com/problems/delete-node-in-a-linked-list/description/", codeSolution: "https://edslash.com/leetcode-problem-237-delete-node-in-a-linked-list/", video: "https://youtu.be/dDiONeufV4Y" },
  { day: 70, name: "Linked List Cycle", topic: "Linked List", leetcode: "https://leetcode.com/problems/linked-list-cycle/", codeSolution: "https://edslash.com/leetcode-problem-141-linked-list-cycle/", video: "https://youtu.be/T1SJ9IRwbx0" },
  { day: 71, name: "Linked List Cycle II", topic: "Linked List", leetcode: "https://leetcode.com/problems/linked-list-cycle-ii/", codeSolution: "https://edslash.com/leetcode-problem-142-linked-list-cycle-ii/", video: "https://youtu.be/MJ6Xujy_5Aw" },
  { day: 72, name: "Remove Linked List Elements", topic: "Linked List", leetcode: "https://leetcode.com/problems/remove-linked-list-elements/", codeSolution: "https://edslash.com/leetcode-problem-203-remove-linked-list-elements/", video: "https://youtu.be/cDVDLFLQgoM" },
  { day: 73, name: "Next Greater Node in Linked List", topic: "Linked List", leetcode: "https://leetcode.com/problems/next-greater-node-in-linked-list/description/", codeSolution: "https://edslash.com/leetcode-problem-1019-next-greater-node-in-linked-list/", video: "https://youtu.be/iE_HnWIZbKk" },
  { day: 74, name: "Delete the Middle Node of a Linked List", topic: "Linked List", leetcode: "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/", codeSolution: "https://edslash.com/leetcode-problem-2095-delete-the-middle-node-of-a-linked-list/", video: "https://youtu.be/DRA2qlGuUPI" },
  { day: 75, name: "Merge Nodes in Between Zeros", topic: "Linked List", leetcode: "https://leetcode.com/problems/merge-nodes-in-between-zeros/description/", codeSolution: "https://edslash.com/leetcode-problem-2181-merge-nodes-in-between-zeros/", video: "https://youtu.be/7lF9UlNBb8M" },
  { day: 76, name: "Merge K Sorted Lists", topic: "Linked List", leetcode: "https://leetcode.com/problems/merge-k-sorted-lists/description/", codeSolution: "https://edslash.com/leetcode-problem-23-merge-k-sorted-lists/", video: "https://youtu.be/ruVHEtZWv3A" },

  // ===== Binary Tree (Days 77-91) =====
  { day: 77, name: "Univalued Binary Tree", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/univalued-binary-tree/", codeSolution: "https://edslash.com/leetcode-problem-965-univalued-binary-tree/", video: "https://youtu.be/oR6T-xiahoA" },
  { day: 78, name: "Count Complete Tree Nodes", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/count-complete-tree-nodes/", codeSolution: "https://edslash.com/leetcode-problem-222-count-complete-tree-nodes/", video: "https://youtu.be/CNjJg0WKdyo" },
  { day: 79, name: "Symmetric Tree", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/symmetric-tree/", codeSolution: "https://edslash.com/leetcode-problem-101-symmetric-tree/", video: "https://youtu.be/5ioJWEnD4R0" },
  { day: 80, name: "Binary Tree Postorder Traversal", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/binary-tree-postorder-traversal/", codeSolution: "https://edslash.com/leetcode-problem-145-binary-tree-postorder-traversal/", video: "https://youtu.be/Lkz9bYynoa0" },
  { day: 81, name: "Binary Tree Level Order Traversal", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/binary-tree-level-order-traversal/description/", codeSolution: "https://edslash.com/leetcode-problem-102-binary-tree-level-order-traversal/", video: "https://youtu.be/wWTyb320tT0" },
  { day: 82, name: "Binary Tree Paths", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/binary-tree-paths/description/", codeSolution: "https://edslash.com/leetcode-problem-257-binary-tree-paths", video: "https://youtu.be/4tDwBO5Cugg" },
  { day: 83, name: "Binary Tree Zigzag Level Order Traversal", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", codeSolution: "https://edslash.com/leetcode-problem-103-binary-tree-zigzag-level-order-traversal/", video: "https://youtu.be/5hiLe1GsiKc" },
  { day: 84, name: "Balanced Binary Tree", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/balanced-binary-tree/", codeSolution: "https://edslash.com/leetcode-problem-110-balanced-binary-tree/", video: "https://youtu.be/wvhPuDvnkig" },
  { day: 85, name: "Kth Smallest Element in a BST", topic: "BST", leetcode: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", codeSolution: "https://edslash.com/leetcode-problem-230-kth-smallest-element-in-a-bst/", video: "https://youtu.be/RGKUF9vvZnU" },
  { day: 86, name: "Path Sum", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/path-sum/", codeSolution: "https://edslash.com/leetcode-problem-112-path-sum", video: "https://youtu.be/c-XCfhUMs5U" },
  { day: 87, name: "Binary Tree Right Side View", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/binary-tree-right-side-view/", codeSolution: "https://edslash.com/leetcode-problem-199-binary-tree-right-side-view/", video: "https://youtu.be/bfdCYfUd7yg" },
  { day: 88, name: "Invert Binary Tree", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/invert-binary-tree/", codeSolution: "https://edslash.com/leetcode-problem-226-invert-binary-tree/", video: "https://youtu.be/4VErA2LkQ-w" },
  { day: 89, name: "Diameter of Binary Tree", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/diameter-of-binary-tree/", codeSolution: "https://edslash.com/leetcode-problem-543-diameter-of-binary-tree/", video: "https://youtu.be/OEdRCnWZlHg" },
  { day: 90, name: "Convert Sorted Array to Binary Search Tree", topic: "BST", leetcode: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/description/", codeSolution: "https://edslash.com/leetcode-problem-108-convert-sorted-array-to-binary-search-tree/", video: "https://youtu.be/c_o05s9WbLg" },
  { day: 91, name: "Merge Two Binary Trees", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/merge-two-binary-trees/description/", codeSolution: "https://edslash.com/leetcode-problem-617-merge-two-binary-trees/", video: "https://youtu.be/xX5GBXUj72k" },

  // ===== BST (Days 92-99) =====
  { day: 92, name: "Search in a Binary Search Tree", topic: "BST", leetcode: "https://leetcode.com/problems/search-in-a-binary-search-tree/description/", codeSolution: "https://edslash.com/leetcode-problem-700-search-in-a-binary-search-tree", video: "https://youtu.be/_FPN2_qPbkc" },
  { day: 93, name: "Insert into a Binary Search Tree", topic: "BST", leetcode: "https://leetcode.com/problems/insert-into-a-binary-search-tree/", codeSolution: "https://edslash.com/leetcode-problem-701-insert-into-a-binary-search-tree/", video: "https://youtu.be/vdf7_L8tM_U" },
  { day: 94, name: "Lowest Common Ancestor of a Binary Search Tree", topic: "BST", leetcode: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", codeSolution: "https://edslash.com/leetcode-problem-235-lowest-common-ancestor-of-a-binary-search-tree/", video: "https://youtu.be/oTDLdp8qOWE" },
  { day: 95, name: "Validate Binary Search Tree", topic: "BST", leetcode: "https://leetcode.com/problems/validate-binary-search-tree/description/", codeSolution: "https://edslash.com/leetcode-problem-98-validate-binary-search-tree/", video: "https://youtu.be/wi_q1S65yvg" },
  { day: 96, name: "Convert Sorted List to Binary Search Tree", topic: "BST", leetcode: "https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/description/", codeSolution: "https://edslash.com/leetcode-problem-109-convert-sorted-list-to-binary-search-tree/", video: "https://youtu.be/3EczvGBv-Jc" },
  { day: 97, name: "Balance a Binary Search Tree", topic: "BST", leetcode: "https://leetcode.com/problems/balance-a-binary-search-tree/", codeSolution: "https://edslash.com/leetcode-problem-1382-balance-a-binary-search-tree/", video: "https://youtu.be/IkorpeTfwsM" },
  { day: 98, name: "Deepest Leaves Sum", topic: "Binary Tree", leetcode: "https://leetcode.com/problems/deepest-leaves-sum/description/", codeSolution: "https://edslash.com/leetcode-problem-1302-deepest-leaves-sum", video: "https://youtu.be/g_-SJw1Za2A" },
  { day: 99, name: "Binary Search Tree to Greater Sum Tree", topic: "BST", leetcode: "https://leetcode.com/problems/binary-search-tree-to-greater-sum-tree/", codeSolution: "https://edslash.com/leetcode-problem-1038-binary-search-tree-to-greater-sum-tree/", video: "https://youtu.be/tVq0ekZ_yFM" },

  // ===== Bonus (Day 100) =====
  { day: 100, name: "Best Time to Buy and Sell Stock", topic: "Arrays", leetcode: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", codeSolution: "https://edslash.com/leetcode-problem-121-best-time-to-buy-and-sell-stock/", video: "https://youtu.be/aic6SSdpAj8" },
];

export const topicsList = ["All", "Basics", "Arrays", "Binary Search", "Sorting", "Stack & Queue", "Strings", "Matrix", "Linked List", "Binary Tree", "BST"];

export const topicColors = {
  "Basics": { bg: "bg-violet-500/15", text: "text-violet-400", border: "border-violet-500/30", activeBg: "bg-violet-500", dot: "bg-violet-500" },
  "Arrays": { bg: "bg-blue-500/15", text: "text-blue-400", border: "border-blue-500/30", activeBg: "bg-blue-500", dot: "bg-blue-500" },
  "Binary Search": { bg: "bg-cyan-500/15", text: "text-cyan-400", border: "border-cyan-500/30", activeBg: "bg-cyan-500", dot: "bg-cyan-500" },
  "Sorting": { bg: "bg-amber-500/15", text: "text-amber-400", border: "border-amber-500/30", activeBg: "bg-amber-500", dot: "bg-amber-500" },
  "Stack & Queue": { bg: "bg-pink-500/15", text: "text-pink-400", border: "border-pink-500/30", activeBg: "bg-pink-500", dot: "bg-pink-500" },
  "Strings": { bg: "bg-orange-500/15", text: "text-orange-400", border: "border-orange-500/30", activeBg: "bg-orange-500", dot: "bg-orange-500" },
  "Matrix": { bg: "bg-teal-500/15", text: "text-teal-400", border: "border-teal-500/30", activeBg: "bg-teal-500", dot: "bg-teal-500" },
  "Linked List": { bg: "bg-rose-500/15", text: "text-rose-400", border: "border-rose-500/30", activeBg: "bg-rose-500", dot: "bg-rose-500" },
  "Binary Tree": { bg: "bg-lime-500/15", text: "text-lime-400", border: "border-lime-500/30", activeBg: "bg-lime-500", dot: "bg-lime-500" },
  "BST": { bg: "bg-emerald-500/15", text: "text-emerald-400", border: "border-emerald-500/30", activeBg: "bg-emerald-500", dot: "bg-emerald-500" },
};

export default hundredDaysData;
